/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Erik
 */
public class AdminNyForestandare extends javax.swing.JFrame {

    private static InfDB idb;

    /**
     * Creates new form AdminNyForestandare
     */
    public AdminNyForestandare(String txtelevhemssokning) {
        initComponents();
        txtelevhemres.setText(txtelevhemssokning);

        try {
            idb = new InfDB("C://db//HOGDB.FDB"); //hämtar databasen HOGDB.FDB och namnger med ett variabelnamnet InfDB
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    public AdminNyForestandare() {
        initComponents();

    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdminNyForestandare = new javax.swing.JPanel();
        lblnyttforestandareid = new javax.swing.JLabel();
        txtnyforestandare = new javax.swing.JTextField();
        Andra = new javax.swing.JButton();
        txtelevhemres = new javax.swing.JTextField();
        lblelevhem = new javax.swing.JLabel();
        txtforestandare = new javax.swing.JTextField();
        lblforestandare = new javax.swing.JLabel();
        Hamtaid = new javax.swing.JButton();
        txtlarareid = new javax.swing.JTextField();
        txtlararenamn = new javax.swing.JTextField();
        lbllararenamn = new javax.swing.JLabel();
        Tillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnyttforestandareid.setText("Skriv in den nya föreståndaren id");

        Andra.setText("Ändra");
        Andra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraActionPerformed(evt);
            }
        });

        txtelevhemres.setEditable(false);
        txtelevhemres.setBackground(new java.awt.Color(204, 204, 255));

        lblelevhem.setText("Ändrar för elevhem");

        txtforestandare.setBackground(new java.awt.Color(204, 204, 255));
        txtforestandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtforestandareActionPerformed(evt);
            }
        });

        lblforestandare.setText("Nuvarande föreståndare");

        Hamtaid.setText("Hämta ID");
        Hamtaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HamtaidActionPerformed(evt);
            }
        });

        lbllararenamn.setText("Skriv in lärarens namn");

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminNyForestandareLayout = new javax.swing.GroupLayout(PanelAdminNyForestandare);
        PanelAdminNyForestandare.setLayout(PanelAdminNyForestandareLayout);
        PanelAdminNyForestandareLayout.setHorizontalGroup(
            PanelAdminNyForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminNyForestandareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAdminNyForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdminNyForestandareLayout.createSequentialGroup()
                        .addGroup(PanelAdminNyForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnyttforestandareid)
                            .addGroup(PanelAdminNyForestandareLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(txtnyforestandare, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAdminNyForestandareLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(Andra)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminNyForestandareLayout.createSequentialGroup()
                        .addGroup(PanelAdminNyForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbllararenamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelAdminNyForestandareLayout.createSequentialGroup()
                                .addGap(0, 17, Short.MAX_VALUE)
                                .addGroup(PanelAdminNyForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblforestandare)
                                    .addComponent(lblelevhem))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelAdminNyForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtforestandare, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtelevhemres, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminNyForestandareLayout.createSequentialGroup()
                        .addComponent(txtlararenamn)
                        .addGap(18, 18, 18)
                        .addComponent(Hamtaid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelAdminNyForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tillbaka)
                            .addComponent(txtlarareid, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        PanelAdminNyForestandareLayout.setVerticalGroup(
            PanelAdminNyForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminNyForestandareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAdminNyForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtelevhemres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblelevhem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAdminNyForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtforestandare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblforestandare))
                .addGap(18, 18, 18)
                .addComponent(lbllararenamn)
                .addGap(9, 9, 9)
                .addGroup(PanelAdminNyForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hamtaid)
                    .addComponent(txtlararenamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlarareid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblnyttforestandareid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnyforestandare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Andra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminNyForestandare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminNyForestandare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtnyforestandare))
            try {

                idb.update("update ELEVHEM set FORESTANDARE ='" + txtnyforestandare.getText() + "' where ELEVHEMSNAMN = '" + txtelevhemres.getText() + "'");

                JOptionPane.showMessageDialog(null, "Informationen har ändrats");

                new AdminMeny().setVisible(true);
                this.setVisible(false);
            } catch (InfException e) {

                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());

  }
    }//GEN-LAST:event_AndraActionPerformed

    private void txtforestandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtforestandareActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtelevhemres)) // Kallar på valideringsklassen för att kontrollera att textfältet är tomt. 
        {
            try {
                String elevhem = txtelevhemres.getText();
                String Forstandaresearch = idb.fetchSingle("select FORESTANDARE from ELEVHEM where ELEVHEMSNAMN ='" + elevhem + "'"); // hämtar föreståndare från elevhem och lägger i String Förestandarsearch.
                ArrayList<HashMap<String, String>> forstandareidsearch = idb.fetchRows("select FORNAMN,EFTERNAMN from LARARE where LARAR_ID ='" + Forstandaresearch + "'"); // Placerar förnamn och efternamn från lärare i en arraylist of hashmap.

                txtforestandare.setText(forstandareidsearch.toString()); // Konverterar till Sttring och placerar förestandareidsearch i txtforestandare. 

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());
            }
        }

    }//GEN-LAST:event_txtforestandareActionPerformed

    private void HamtaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HamtaidActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtlararenamn)) {
            try {
                String lararenamn = txtlararenamn.getText();
                String larareidsearch = idb.fetchSingle("select LARAR_ID from LARARE where FORNAMN ='" + lararenamn + "'");

                txtlarareid.setText(larareidsearch);

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());
            }
        }


    }//GEN-LAST:event_HamtaidActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        // TODO add your handling code here:
        this.hide();
        AdminMeny frm = new AdminMeny();
        frm.setVisible(true);


    }//GEN-LAST:event_TillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminNyForestandare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminNyForestandare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminNyForestandare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminNyForestandare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminNyForestandare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Andra;
    private javax.swing.JButton Hamtaid;
    private javax.swing.JPanel PanelAdminNyForestandare;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JLabel lblelevhem;
    private javax.swing.JLabel lblforestandare;
    private javax.swing.JLabel lbllararenamn;
    private javax.swing.JLabel lblnyttforestandareid;
    private javax.swing.JTextField txtelevhemres;
    private javax.swing.JTextField txtforestandare;
    private javax.swing.JTextField txtlarareid;
    private javax.swing.JTextField txtlararenamn;
    private javax.swing.JTextField txtnyforestandare;
    // End of variables declaration//GEN-END:variables
}
