/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Jerka
 */
public class AdminSkrivNyttElevhemsPoang extends javax.swing.JFrame {
    private static InfDB idb;
//public static String txtelevhem;

    /**
     * Creates new form SkrivNyttElevhemsPoang
     */
    public AdminSkrivNyttElevhemsPoang(String txtelevhem) {
        initComponents();
        txtelevhemsnamn.setText(txtelevhem);
        try {
            idb = new InfDB("C://db//HOGDB.FDB");

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    public AdminSkrivNyttElevhemsPoang() {
        initComponents();

    }

//public SkrivNyttElevhemsPoang(String para){
    //      initComponents();
    //   txtelevhem.setText(para);
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdminSkrivNyttElevhemspoang = new javax.swing.JPanel();
        lblpoang = new javax.swing.JLabel();
        Registrera = new javax.swing.JButton();
        txtelevhemsnamn = new javax.swing.JTextField();
        lblelevhem = new javax.swing.JLabel();
        Tillbaka = new javax.swing.JButton();
        valjannatelevhem = new javax.swing.JButton();
        txtpoang = new javax.swing.JTextField();
        lbltoptext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblpoang.setText("Skriv in nya poäng");

        Registrera.setText("Registrera");
        Registrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistreraActionPerformed(evt);
            }
        });

        txtelevhemsnamn.setBackground(new java.awt.Color(204, 204, 255));
        txtelevhemsnamn.setCaretColor(new java.awt.Color(204, 204, 204));

        lblelevhem.setText("Ändrar följande elevhems poäng");

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        valjannatelevhem.setText("Välj ett annat elevhem");
        valjannatelevhem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valjannatelevhemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminSkrivNyttElevhemspoangLayout = new javax.swing.GroupLayout(PanelAdminSkrivNyttElevhemspoang);
        PanelAdminSkrivNyttElevhemspoang.setLayout(PanelAdminSkrivNyttElevhemspoangLayout);
        PanelAdminSkrivNyttElevhemspoangLayout.setHorizontalGroup(
            PanelAdminSkrivNyttElevhemspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminSkrivNyttElevhemspoangLayout.createSequentialGroup()
                .addGroup(PanelAdminSkrivNyttElevhemspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdminSkrivNyttElevhemspoangLayout.createSequentialGroup()
                        .addComponent(valjannatelevhem)
                        .addGap(18, 18, 18)
                        .addComponent(Tillbaka))
                    .addComponent(lblpoang)
                    .addComponent(txtpoang, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registrera)
                    .addGroup(PanelAdminSkrivNyttElevhemspoangLayout.createSequentialGroup()
                        .addComponent(lblelevhem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtelevhemsnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PanelAdminSkrivNyttElevhemspoangLayout.setVerticalGroup(
            PanelAdminSkrivNyttElevhemspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminSkrivNyttElevhemspoangLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelAdminSkrivNyttElevhemspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblelevhem)
                    .addComponent(txtelevhemsnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblpoang)
                .addGap(18, 18, 18)
                .addComponent(txtpoang, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Registrera)
                .addGap(37, 37, 37)
                .addGroup(PanelAdminSkrivNyttElevhemspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valjannatelevhem)
                    .addComponent(Tillbaka))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltoptext.setText("Registrera huspoäng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelAdminSkrivNyttElevhemspoang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltoptext))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbltoptext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAdminSkrivNyttElevhemspoang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistreraActionPerformed
        if (Validering.textNotEmpty(txtpoang)) {
            try {
                String NyaPoang = txtpoang.getText();
                String elevhemsnamn = txtelevhemsnamn.getText();

                idb.update("UPDATE ELEVHEM SET HUSPOANG = '" + NyaPoang + "' where ELEVHEMSNAMN ='" + elevhemsnamn + "'");
                JOptionPane.showMessageDialog(null, " " + elevhemsnamn + " har tilldelats " + NyaPoang + " poäng!");
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());

            }
        }

    }//GEN-LAST:event_RegistreraActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        this.hide();
        AdminMeny frm = new AdminMeny();
        frm.setVisible(true);

// Tar användaren tillbaka till huvudmenyn
    }//GEN-LAST:event_TillbakaActionPerformed

    private void valjannatelevhemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valjannatelevhemActionPerformed
        // TODO add your handling code here:
        this.hide();
        AdminRegHuspoang frm = new AdminRegHuspoang();
        frm.setVisible(true);

    }//GEN-LAST:event_valjannatelevhemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //txtelevhem=args[0];
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSkrivNyttElevhemsPoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSkrivNyttElevhemsPoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSkrivNyttElevhemsPoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSkrivNyttElevhemsPoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSkrivNyttElevhemsPoang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdminSkrivNyttElevhemspoang;
    private javax.swing.JButton Registrera;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JLabel lblelevhem;
    private javax.swing.JLabel lblpoang;
    private javax.swing.JLabel lbltoptext;
    public javax.swing.JTextField txtelevhemsnamn;
    public javax.swing.JTextField txtpoang;
    private javax.swing.JButton valjannatelevhem;
    // End of variables declaration//GEN-END:variables
}
