/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Erik
 */
public class AdminNyregLarare extends javax.swing.JFrame {

    private static InfDB idb;

    /**
     * Creates new form AdminNyregLarare
     */
    public AdminNyregLarare() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdminNyRegLarare = new javax.swing.JPanel();
        lblTopText = new javax.swing.JLabel();
        txtlarareid = new javax.swing.JTextField();
        lblLarareID = new javax.swing.JLabel();
        txtfornamn = new javax.swing.JTextField();
        txtefternamn = new javax.swing.JTextField();
        txtlosenord = new javax.swing.JTextField();
        Register = new javax.swing.JButton();
        lblFornamn = new javax.swing.JLabel();
        lblefternamn = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        Tillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTopText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTopText.setText("Nyregistrera en lärare");

        lblLarareID.setText("Lärare ID");

        Register.setText("Registrera");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        lblFornamn.setText("Fornamn");

        lblefternamn.setText("Efternamn");

        lblpassword.setText("Lösenord");

        javax.swing.GroupLayout PanelAdminNyRegLarareLayout = new javax.swing.GroupLayout(PanelAdminNyRegLarare);
        PanelAdminNyRegLarare.setLayout(PanelAdminNyRegLarareLayout);
        PanelAdminNyRegLarareLayout.setHorizontalGroup(
            PanelAdminNyRegLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminNyRegLarareLayout.createSequentialGroup()
                .addGroup(PanelAdminNyRegLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdminNyRegLarareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelAdminNyRegLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTopText)
                            .addGroup(PanelAdminNyRegLarareLayout.createSequentialGroup()
                                .addComponent(lblFornamn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAdminNyRegLarareLayout.createSequentialGroup()
                                .addComponent(lblefternamn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtefternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAdminNyRegLarareLayout.createSequentialGroup()
                                .addComponent(lblLarareID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtlarareid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAdminNyRegLarareLayout.createSequentialGroup()
                                .addComponent(lblpassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtlosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelAdminNyRegLarareLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PanelAdminNyRegLarareLayout.setVerticalGroup(
            PanelAdminNyRegLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminNyRegLarareLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopText)
                .addGap(37, 37, 37)
                .addGroup(PanelAdminNyRegLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlarareid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLarareID))
                .addGap(18, 18, 18)
                .addGroup(PanelAdminNyRegLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornamn)
                    .addComponent(txtfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PanelAdminNyRegLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblefternamn)
                    .addComponent(txtefternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PanelAdminNyRegLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword)
                    .addComponent(txtlosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Register)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelAdminNyRegLarare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tillbaka, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelAdminNyRegLarare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Tillbaka)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtlarareid)) {
            try {

                String Larareid = txtlarareid.getText();
                String fornamn = txtfornamn.getText();
                String efternamn = txtefternamn.getText();
                String password = txtlosenord.getText();

                idb.insert("INSERT INTO LARARE(LARAR_ID, FORNAMN, EFTERNAMN, LOSENORD, ADMINISTRATOR) VALUES('" + Larareid + "','" + fornamn + "','" + efternamn + "','" + password + "','F')");

                JOptionPane.showMessageDialog(null, "Läraren : " + fornamn + " " + efternamn + " lades till med LärareID : " + Larareid + " med lösenordert : " + password + "!");
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println("Internt felmeddelande" + e.getMessage());
            }
        }


    }//GEN-LAST:event_RegisterActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        // TODO add your handling code here:
        this.hide();
        AdminMeny frm = new AdminMeny();
        frm.setVisible(true);

    }//GEN-LAST:event_TillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminNyregLarare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminNyregLarare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminNyregLarare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminNyregLarare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminNyregLarare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdminNyRegLarare;
    private javax.swing.JButton Register;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblLarareID;
    private javax.swing.JLabel lblTopText;
    private javax.swing.JLabel lblefternamn;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JTextField txtefternamn;
    private javax.swing.JTextField txtfornamn;
    private javax.swing.JTextField txtlarareid;
    private javax.swing.JTextField txtlosenord;
    // End of variables declaration//GEN-END:variables
}
