/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Erik
 */
public class AdminChangeElevhemForstandare extends javax.swing.JFrame {

    private static InfDB idb;

    /**
     * Creates new form AdminChangeElevhemForstandare
     */
    public AdminChangeElevhemForstandare() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB"); //hämtar databasen HOGDB.FDB och namnger med ett variabelnamnet InfDB
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");  //felmedellande 
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdminChangeElevhemsForestandare = new javax.swing.JPanel();
        lblValjElevhem = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        Valj = new javax.swing.JButton();
        ComboBoxElevhem = new javax.swing.JComboBox<>();
        txtelevhemsokning = new javax.swing.JTextField();
        lblTopText = new javax.swing.JLabel();
        Tillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValjElevhem.setText("Välj elevhemmet");

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        Valj.setText("Välj");
        Valj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValjActionPerformed(evt);
            }
        });

        ComboBoxElevhem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gryffindor", "Ravenclaw", "Slytherin", "Hufflepuff\t" }));

        txtelevhemsokning.setText("<Inget elevhem har valts>");

        lblTopText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTopText.setText("Ändra förståndare för ett elevhem");

        javax.swing.GroupLayout PanelAdminChangeElevhemsForestandareLayout = new javax.swing.GroupLayout(PanelAdminChangeElevhemsForestandare);
        PanelAdminChangeElevhemsForestandare.setLayout(PanelAdminChangeElevhemsForestandareLayout);
        PanelAdminChangeElevhemsForestandareLayout.setHorizontalGroup(
            PanelAdminChangeElevhemsForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminChangeElevhemsForestandareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAdminChangeElevhemsForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValjElevhem)
                    .addComponent(OK)
                    .addGroup(PanelAdminChangeElevhemsForestandareLayout.createSequentialGroup()
                        .addComponent(ComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Valj))
                    .addComponent(txtelevhemsokning, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTopText))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        PanelAdminChangeElevhemsForestandareLayout.setVerticalGroup(
            PanelAdminChangeElevhemsForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminChangeElevhemsForestandareLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValjElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAdminChangeElevhemsForestandareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtelevhemsokning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OK)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelAdminChangeElevhemsForestandare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelAdminChangeElevhemsForestandare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtelevhemsokning)) {
            try {
                String elevhem = txtelevhemsokning.getText();
                String Forstandaresearch = idb.fetchSingle("select FORESTANDARE from ELEVHEM where ELEVHEMSNAMN ='" + elevhem + "'");
                ArrayList<HashMap<String, String>> Forstandareidsearch = idb.fetchRows("select FORNAMN,EFTERNAMN from LARARE where LARAR_ID ='" + Forstandaresearch + "'");

                JOptionPane.showMessageDialog(null, "" + elevhem + " har " + Forstandareidsearch + " som föreståndare");

                new AdminNyForestandare(this.txtelevhemsokning.getText()).setVisible(true);
                this.setVisible(false);

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());
            }
        }


    }//GEN-LAST:event_OKActionPerformed

    private void ValjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValjActionPerformed
        // TODO add your handling code here:
        txtelevhemsokning.setText(ComboBoxElevhem.getSelectedItem().toString());
    }//GEN-LAST:event_ValjActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        // TODO add your handling code here:
        this.hide();
        AdminMeny frm = new AdminMeny();
        frm.setVisible(true);

    }//GEN-LAST:event_TillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChangeElevhemForstandare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChangeElevhemForstandare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChangeElevhemForstandare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChangeElevhemForstandare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChangeElevhemForstandare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxElevhem;
    private javax.swing.JButton OK;
    private javax.swing.JPanel PanelAdminChangeElevhemsForestandare;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JButton Valj;
    private javax.swing.JLabel lblTopText;
    private javax.swing.JLabel lblValjElevhem;
    private javax.swing.JTextField txtelevhemsokning;
    // End of variables declaration//GEN-END:variables
}
