/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Erik
 */
public class AdminChangeAdminStatus extends javax.swing.JFrame {

    private static InfDB idb;

    /**
     * Creates new form AdminChangeAdminStatus
     */
    public AdminChangeAdminStatus() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB"); //hämtar databasen HOGDB.FDB och namnger med ett variabelnamnet InfDB
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel"); //felmedellande 
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelforChangeAdminStatus = new javax.swing.JPanel();
        AndraLagTill = new javax.swing.JButton();
        lblinfo = new javax.swing.JLabel();
        txtlararenamn = new javax.swing.JTextField();
        lbltoptext = new javax.swing.JLabel();
        lblinfo1 = new javax.swing.JLabel();
        lblLaggTill = new javax.swing.JLabel();
        lblTabortAdminStatus = new javax.swing.JLabel();
        txttabortadminstatus = new javax.swing.JTextField();
        AndraTaBort = new javax.swing.JButton();
        Tillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AndraLagTill.setText("Ändra");
        AndraLagTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraLagTillActionPerformed(evt);
            }
        });

        lblinfo.setText("Skriv in lärarens förnamn");

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltoptext.setText("Ändra Adminstartörstatus");

        lblinfo1.setText("Skriv in lärarens förnamn");

        lblLaggTill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLaggTill.setText("Lägg till");

        lblTabortAdminStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTabortAdminStatus.setText("Ta bort en lärares adminstatörs status");

        AndraTaBort.setText("Ändra");
        AndraTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraTaBortActionPerformed(evt);
            }
        });

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelforChangeAdminStatusLayout = new javax.swing.GroupLayout(PanelforChangeAdminStatus);
        PanelforChangeAdminStatus.setLayout(PanelforChangeAdminStatusLayout);
        PanelforChangeAdminStatusLayout.setHorizontalGroup(
            PanelforChangeAdminStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelforChangeAdminStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelforChangeAdminStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelforChangeAdminStatusLayout.createSequentialGroup()
                        .addComponent(AndraTaBort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tillbaka))
                    .addGroup(PanelforChangeAdminStatusLayout.createSequentialGroup()
                        .addGroup(PanelforChangeAdminStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AndraLagTill)
                            .addComponent(lblinfo)
                            .addComponent(lbltoptext)
                            .addComponent(lblLaggTill)
                            .addComponent(lblTabortAdminStatus)
                            .addGroup(PanelforChangeAdminStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txttabortadminstatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(txtlararenamn, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblinfo1))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelforChangeAdminStatusLayout.setVerticalGroup(
            PanelforChangeAdminStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelforChangeAdminStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltoptext)
                .addGap(18, 18, 18)
                .addComponent(lblLaggTill)
                .addGap(14, 14, 14)
                .addComponent(lblinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtlararenamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AndraLagTill)
                .addGap(35, 35, 35)
                .addComponent(lblTabortAdminStatus)
                .addGap(18, 18, 18)
                .addComponent(lblinfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttabortadminstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AndraTaBort)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelforChangeAdminStatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelforChangeAdminStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelforChangeAdminStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AndraLagTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraLagTillActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtlararenamn)) // Kallar på valideringsklassen för att kontrollera att textfältet är tomt. 
        {
            try {
                String lararenamn = txtlararenamn.getText();
                idb.update("UPDATE LARARE SET ADMINISTRATOR = 'T' Where FORNAMN = '" + lararenamn + "'");
                JOptionPane.showMessageDialog(null, "Läraren " + lararenamn + " har nu adminstratörbehörighet och kan logga in!");

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel"); // Felmeddelande
                System.out.println("Internt felmeddelande" + e.getMessage());
            }
        }


    }//GEN-LAST:event_AndraLagTillActionPerformed

    private void AndraTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraTaBortActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txttabortadminstatus)) // Kontrollerar att textfältet är tomt. 
        {
            try {
                String lararenamn = txttabortadminstatus.getText();    // hämtar ut texten från textfältet och placerar den i String lararenamn
                idb.update("UPDATE LARARE SET ADMINISTRATOR = 'F' Where FORNAMN = '" + lararenamn + "'");  // Uppdaterar databasen.
                JOptionPane.showMessageDialog(null, "Läraren " + lararenamn + " har nu ingen adminstratörbehörighet och kan inte längre logga in!");

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel. Försök igen.");             // Felmedelande
                System.out.println("Internt felmeddelande" + e.getMessage());

            }
        }
    }//GEN-LAST:event_AndraTaBortActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        // TODO add your handling code here:
        this.hide();
        AdminMeny frm = new AdminMeny();
        frm.setVisible(true);


    }//GEN-LAST:event_TillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChangeAdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChangeAdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChangeAdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChangeAdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChangeAdminStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AndraLagTill;
    private javax.swing.JButton AndraTaBort;
    private javax.swing.JPanel PanelforChangeAdminStatus;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JLabel lblLaggTill;
    private javax.swing.JLabel lblTabortAdminStatus;
    private javax.swing.JLabel lblinfo;
    private javax.swing.JLabel lblinfo1;
    private javax.swing.JLabel lbltoptext;
    private javax.swing.JTextField txtlararenamn;
    private javax.swing.JTextField txttabortadminstatus;
    // End of variables declaration//GEN-END:variables
}
