/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;


import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Erik
 */
public class AdminChangeKursinfo extends javax.swing.JFrame {
     private static InfDB idb;

    /**
     * Creates new form AdminChangeLarareinfo
     */
    public AdminChangeKursinfo() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB"); //hämtar databasen HOGDB.FDB och namnger med ett variabelnamnet InfDB
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel"); //felmedellande 
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdminChangeKursinformation = new javax.swing.JPanel();
        lblToptext = new javax.swing.JLabel();
        lblkursnamn = new javax.swing.JLabel();
        txtkursnamnsokning = new javax.swing.JTextField();
        lblkursstart = new javax.swing.JLabel();
        txtkursstart = new javax.swing.JTextField();
        lblkursslut = new javax.swing.JLabel();
        txtkursslut = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        fetchid = new javax.swing.JButton();
        txtkursid = new javax.swing.JTextField();
        lblkursid = new javax.swing.JLabel();
        lblinfotext = new javax.swing.JLabel();
        txtnyttid = new javax.swing.JTextField();
        lblnyttid = new javax.swing.JLabel();
        lblnyttkursnamn = new javax.swing.JLabel();
        txtkursnamn = new javax.swing.JTextField();
        Tillbaka = new javax.swing.JButton();
        lblkurslarare = new javax.swing.JLabel();
        txtkurslarare = new javax.swing.JTextField();
        txtamnestillhorighet = new javax.swing.JTextField();
        lblamnestillorighet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblToptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblToptext.setText("Ändra kursinformation");

        lblkursnamn.setText("Kursens namn");

        lblkursstart.setText("Kursstart");

        lblkursslut.setText("Kursslut");

        Update.setText("Ändra");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        fetchid.setText("Hämta ID");
        fetchid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchidActionPerformed(evt);
            }
        });

        lblkursid.setText("Kursens ID");

        lblinfotext.setText("Skriv in ett kursnamn, hämta sedan ID, fyll i de andra fälten");

        lblnyttid.setText("Nytt ID");

        lblnyttkursnamn.setText("Kursnamn");

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        lblkurslarare.setText("Kurslärare");

        lblamnestillorighet.setText("Ämnestillhörighet");

        javax.swing.GroupLayout PanelAdminChangeKursinformationLayout = new javax.swing.GroupLayout(PanelAdminChangeKursinformation);
        PanelAdminChangeKursinformation.setLayout(PanelAdminChangeKursinformationLayout);
        PanelAdminChangeKursinformationLayout.setHorizontalGroup(
            PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminChangeKursinformationLayout.createSequentialGroup()
                .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdminChangeKursinformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblkursslut))
                    .addGroup(PanelAdminChangeKursinformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtkursslut, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAdminChangeKursinformationLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAdminChangeKursinformationLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblinfotext))
                            .addComponent(lblToptext)))
                    .addGroup(PanelAdminChangeKursinformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelAdminChangeKursinformationLayout.createSequentialGroup()
                                .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelAdminChangeKursinformationLayout.createSequentialGroup()
                                        .addComponent(txtkursnamnsokning, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fetchid))
                                    .addComponent(lblkursnamn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblkursid)
                                    .addComponent(txtkursid, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAdminChangeKursinformationLayout.createSequentialGroup()
                                .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Update, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAdminChangeKursinformationLayout.createSequentialGroup()
                                        .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblkursstart)
                                                .addComponent(txtkursstart, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                                .addComponent(lblnyttkursnamn)
                                                .addComponent(txtkursnamn))
                                            .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtnyttid, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblnyttid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtkurslarare, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblkurslarare))
                                        .addGap(52, 52, 52)
                                        .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblamnestillorighet)
                                            .addGroup(PanelAdminChangeKursinformationLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(txtamnestillhorighet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminChangeKursinformationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Tillbaka)))
                .addContainerGap())
        );
        PanelAdminChangeKursinformationLayout.setVerticalGroup(
            PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminChangeKursinformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblToptext)
                .addGap(8, 8, 8)
                .addComponent(lblinfotext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkursid)
                    .addComponent(lblkursnamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fetchid)
                    .addComponent(txtkursid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkursnamnsokning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnyttid)
                    .addComponent(lblkurslarare)
                    .addComponent(lblamnestillorighet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAdminChangeKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnyttid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkurslarare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtamnestillhorighet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblnyttkursnamn)
                .addGap(5, 5, 5)
                .addComponent(txtkursnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblkursstart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtkursstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblkursslut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtkursslut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminChangeKursinformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminChangeKursinformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtkursnamn)) // Kontrollerar att textrutan är tomm.
        {
            try {

                idb.update("update KURS set KURSNAMN ='" + txtkursnamn.getText() + "', KURSSTART ='" + txtkursstart.getText() + "', KURSSLUT ='" + txtkursslut.getText() + "', KURSLARARE ='" + txtkurslarare.getText() + "', AMNESTILLHORIGHET ='" + txtamnestillhorighet.getText() + "', KURS_ID ='" + txtnyttid.getText() + "' where KURS_ID = '" + txtkursid.getText() + "'");

                JOptionPane.showMessageDialog(null, "Informationen har ändrats");
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());

            }
        }


    }//GEN-LAST:event_UpdateActionPerformed

    private void fetchidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchidActionPerformed
        // hämtar ut id

        if (Validering.textNotEmpty(txtkursnamnsokning)) {
            try {
                String kursnamn = txtkursnamnsokning.getText();
                String kursidsearch = idb.fetchSingle("select KURS_ID from KURS where KURSNAMN ='" + kursnamn + "'");

                txtkursid.setText(kursidsearch);
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println("Internt felmeddelande" + e.getMessage());
            }
        }
        
    }//GEN-LAST:event_fetchidActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        // TODO add your handling code here:
this.hide();
AdminMeny frm = new AdminMeny();
frm.setVisible(true);            
        
    }//GEN-LAST:event_TillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChangeKursinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChangeKursinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChangeKursinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChangeKursinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChangeKursinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdminChangeKursinformation;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JButton Update;
    private javax.swing.JButton fetchid;
    private javax.swing.JLabel lblToptext;
    private javax.swing.JLabel lblamnestillorighet;
    private javax.swing.JLabel lblinfotext;
    private javax.swing.JLabel lblkursid;
    private javax.swing.JLabel lblkurslarare;
    private javax.swing.JLabel lblkursnamn;
    private javax.swing.JLabel lblkursslut;
    private javax.swing.JLabel lblkursstart;
    private javax.swing.JLabel lblnyttid;
    private javax.swing.JLabel lblnyttkursnamn;
    private javax.swing.JTextField txtamnestillhorighet;
    private javax.swing.JTextField txtkursid;
    private javax.swing.JTextField txtkurslarare;
    private javax.swing.JTextField txtkursnamn;
    private javax.swing.JTextField txtkursnamnsokning;
    private javax.swing.JTextField txtkursslut;
    private javax.swing.JTextField txtkursstart;
    private javax.swing.JTextField txtnyttid;
    // End of variables declaration//GEN-END:variables
}
