/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

/**
 *
 * @author Erik
 */
public class AdminMeny extends javax.swing.JFrame {

    /**
     * Creates new form AdminMeny
     */
    public AdminMeny() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdminMeny = new javax.swing.JPanel();
        NyRegLarare = new javax.swing.JButton();
        AndralarareInfo = new javax.swing.JButton();
        Tabortlarare = new javax.swing.JButton();
        AndraElevhemforestandare = new javax.swing.JButton();
        AndraAdminStatus = new javax.swing.JButton();
        NyRegElev = new javax.swing.JButton();
        AndraElevInfo = new javax.swing.JButton();
        Tabortelev = new javax.swing.JButton();
        AndraHuspoang = new javax.swing.JButton();
        AndraElevhemsprefekt = new javax.swing.JButton();
        NyRegKurs = new javax.swing.JButton();
        AndraKursInfo = new javax.swing.JButton();
        Tabortkurs = new javax.swing.JButton();
        TillbakaStartMeny = new javax.swing.JButton();
        lblMenytitel = new javax.swing.JLabel();
        lbltoptext = new javax.swing.JLabel();
        lblkurs = new javax.swing.JLabel();
        lblelever = new javax.swing.JLabel();
        lblkurser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NyRegLarare.setText("Nyregistrera en lärare");
        NyRegLarare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NyRegLarareActionPerformed(evt);
            }
        });

        AndralarareInfo.setText("Ändra lärarinformation");
        AndralarareInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AndralarareInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndralarareInfoActionPerformed(evt);
            }
        });

        Tabortlarare.setText("Ta bort lärare");
        Tabortlarare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabortlarareActionPerformed(evt);
            }
        });

        AndraElevhemforestandare.setText("Ändra elevhemsförståndare ");
        AndraElevhemforestandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraElevhemforestandareActionPerformed(evt);
            }
        });

        AndraAdminStatus.setText("Ge lärare adminstratörstatus");
        AndraAdminStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraAdminStatusActionPerformed(evt);
            }
        });

        NyRegElev.setText("Nyregistrera en elev");
        NyRegElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NyRegElevActionPerformed(evt);
            }
        });

        AndraElevInfo.setText("Ändra information om en elev");
        AndraElevInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraElevInfoActionPerformed(evt);
            }
        });

        Tabortelev.setText("Ta bort en elev");
        Tabortelev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabortelevActionPerformed(evt);
            }
        });

        AndraHuspoang.setText("Ändra Huspoäng");
        AndraHuspoang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraHuspoangActionPerformed(evt);
            }
        });

        AndraElevhemsprefekt.setText("Ändra elevhemsprefekt");
        AndraElevhemsprefekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraElevhemsprefektActionPerformed(evt);
            }
        });

        NyRegKurs.setText("Nyregistrera en kurs");
        NyRegKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NyRegKursActionPerformed(evt);
            }
        });

        AndraKursInfo.setText("Ändra kursinformation");
        AndraKursInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraKursInfoActionPerformed(evt);
            }
        });

        Tabortkurs.setText("Ta bort en kurs");
        Tabortkurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabortkursActionPerformed(evt);
            }
        });

        TillbakaStartMeny.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TillbakaStartMeny.setText("Tillbaka till Startskärm");
        TillbakaStartMeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaStartMenyActionPerformed(evt);
            }
        });

        lblMenytitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMenytitel.setText("Administratör meny");

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltoptext.setText("Välj ett alternativ här nedan");

        lblkurs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblkurs.setText("Lärare");

        lblelever.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblelever.setText("Elever");

        lblkurser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblkurser.setText("Kurser");

        javax.swing.GroupLayout PanelAdminMenyLayout = new javax.swing.GroupLayout(PanelAdminMeny);
        PanelAdminMeny.setLayout(PanelAdminMenyLayout);
        PanelAdminMenyLayout.setHorizontalGroup(
            PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                        .addComponent(lblMenytitel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                        .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminMenyLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(TillbakaStartMeny))
                            .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                                .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                                        .addComponent(AndraAdminStatus)
                                        .addGap(54, 54, 54)
                                        .addComponent(AndraElevhemsprefekt))
                                    .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                                        .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Tabortlarare)
                                            .addComponent(AndraElevhemforestandare)
                                            .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(AndralarareInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(NyRegLarare, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(56, 56, 56)
                                        .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AndraHuspoang)
                                            .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                                                .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Tabortelev)
                                                    .addComponent(AndraElevInfo)
                                                    .addComponent(NyRegElev))
                                                .addGap(63, 63, 63)
                                                .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Tabortkurs)
                                                    .addComponent(lblkurser)
                                                    .addComponent(AndraKursInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(NyRegKurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                .addGap(0, 64, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblkurs)
                        .addGap(195, 195, 195)
                        .addComponent(lblelever))
                    .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(lbltoptext)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelAdminMenyLayout.setVerticalGroup(
            PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblMenytitel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltoptext)
                .addGap(18, 18, 18)
                .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkurs)
                    .addComponent(lblelever)
                    .addComponent(lblkurser))
                .addGap(18, 18, 18)
                .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NyRegLarare)
                    .addComponent(NyRegElev)
                    .addComponent(NyRegKurs))
                .addGap(18, 18, 18)
                .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AndralarareInfo)
                    .addComponent(AndraElevInfo)
                    .addComponent(AndraKursInfo))
                .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AndraElevhemforestandare)
                            .addComponent(AndraHuspoang))
                        .addGap(12, 12, 12)
                        .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AndraAdminStatus)
                            .addComponent(AndraElevhemsprefekt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(TillbakaStartMeny)
                        .addContainerGap())
                    .addGroup(PanelAdminMenyLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tabortlarare)
                            .addComponent(Tabortelev)
                            .addComponent(Tabortkurs))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminMeny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelAdminMeny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TillbakaStartMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaStartMenyActionPerformed
        // TODO add your handling code here:

        this.hide();
        HuvudMeny frm = new HuvudMeny();
        frm.setVisible(true);

    }//GEN-LAST:event_TillbakaStartMenyActionPerformed

    private void TabortlarareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabortlarareActionPerformed
        // TODO add your handling code here:
        new AdminTabortLarare().setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_TabortlarareActionPerformed

    private void NyRegLarareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NyRegLarareActionPerformed
        // TODO add your handling code here:

        new AdminNyregLarare().setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_NyRegLarareActionPerformed

    private void NyRegKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NyRegKursActionPerformed
        // TODO add your handling code here:
        new AdminNyregisteraKurser().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_NyRegKursActionPerformed

    private void NyRegElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NyRegElevActionPerformed
        // TODO add your handling code here:
        new AdminNyregElev().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NyRegElevActionPerformed

    private void TabortelevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabortelevActionPerformed
        // TODO add your handling code here:
        new AdminTabortElev().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_TabortelevActionPerformed

    private void TabortkursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabortkursActionPerformed
        // TODO add your handling code here:
        new AdminTabortKurs().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TabortkursActionPerformed

    private void AndralarareInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndralarareInfoActionPerformed
        // TODO add your handling code here:
        new AdminChangeLarareinfo().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_AndralarareInfoActionPerformed

    private void AndraElevInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraElevInfoActionPerformed
        // TODO add your handling code here:
        new AdminChangeElevinfo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AndraElevInfoActionPerformed

    private void AndraKursInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraKursInfoActionPerformed
        // TODO add your handling code here:
        new AdminChangeKursinfo().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_AndraKursInfoActionPerformed

    private void AndraHuspoangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraHuspoangActionPerformed
        // TODO add your handling code here:
        new AdminRegHuspoang().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_AndraHuspoangActionPerformed

    private void AndraElevhemforestandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraElevhemforestandareActionPerformed
        // TODO add your handling code here:
        new AdminChangeElevhemForstandare().setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_AndraElevhemforestandareActionPerformed

    private void AndraAdminStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraAdminStatusActionPerformed
        // TODO add your handling code here:
        new AdminChangeAdminStatus().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_AndraAdminStatusActionPerformed

    private void AndraElevhemsprefektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraElevhemsprefektActionPerformed
        // TODO add your handling code here:
        new AdminChangeElevhemsPrefekt().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_AndraElevhemsprefektActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AndraAdminStatus;
    private javax.swing.JButton AndraElevInfo;
    private javax.swing.JButton AndraElevhemforestandare;
    private javax.swing.JButton AndraElevhemsprefekt;
    private javax.swing.JButton AndraHuspoang;
    private javax.swing.JButton AndraKursInfo;
    private javax.swing.JButton AndralarareInfo;
    private javax.swing.JButton NyRegElev;
    private javax.swing.JButton NyRegKurs;
    private javax.swing.JButton NyRegLarare;
    private javax.swing.JPanel PanelAdminMeny;
    private javax.swing.JButton Tabortelev;
    private javax.swing.JButton Tabortkurs;
    private javax.swing.JButton Tabortlarare;
    private javax.swing.JButton TillbakaStartMeny;
    private javax.swing.JLabel lblMenytitel;
    private javax.swing.JLabel lblelever;
    private javax.swing.JLabel lblkurs;
    private javax.swing.JLabel lblkurser;
    private javax.swing.JLabel lbltoptext;
    // End of variables declaration//GEN-END:variables
}
