/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Erik
 */
public class AdminLogin extends javax.swing.JFrame {

    private static InfDB idb;

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB"); //hämtar databasen HOGDB.FDB och namnger med variabelnamnet InfDB
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdminloggning = new javax.swing.JPanel();
        LblTopText = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        lblanvandare = new javax.swing.JLabel();
        lbllosenord = new javax.swing.JLabel();
        TillStartMenyn = new javax.swing.JButton();
        Loggain = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTopText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblTopText.setText("Administratörsinloggning");

        lblanvandare.setText("Användare/Förnamn");

        lbllosenord.setText("Lösenord");

        TillStartMenyn.setText("Till Startmenyn");
        TillStartMenyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillStartMenynActionPerformed(evt);
            }
        });

        Loggain.setText("Logga in");
        Loggain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoggainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminloggningLayout = new javax.swing.GroupLayout(PanelAdminloggning);
        PanelAdminloggning.setLayout(PanelAdminloggningLayout);
        PanelAdminloggningLayout.setHorizontalGroup(
            PanelAdminloggningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminloggningLayout.createSequentialGroup()
                .addGroup(PanelAdminloggningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdminloggningLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(LblTopText))
                    .addGroup(PanelAdminloggningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAdminloggningLayout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(Loggain)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                            .addComponent(TillStartMenyn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAdminloggningLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(PanelAdminloggningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblanvandare)
                                .addComponent(lbllosenord, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(PanelAdminloggningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addComponent(txtusername)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PanelAdminloggningLayout.setVerticalGroup(
            PanelAdminloggningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminloggningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTopText)
                .addGap(18, 18, 18)
                .addGroup(PanelAdminloggningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblanvandare)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAdminloggningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAdminloggningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Loggain)
                    .addComponent(TillStartMenyn))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminloggning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminloggning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoggainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoggainActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtusername)) // Kallar på valideringsklassen för att kontrollera att textfältet är tomt. 
        {
            try {
                //förnamn används som användarenamn
                String passwordinput = String.valueOf(PasswordField.getPassword());   // Skapar JPasswordField string med namnet passwordinput.
                String fornamn = idb.fetchSingle("select FORNAMN from LARARE where FORNAMN = '" + txtusername.getText() + "'"); // Hämtar ut Förnamn från lärare och placerar i String fornamn.
                String passwordfetch = idb.fetchSingle("Select LOSENORD from LARARE where LOSENORD ='" + passwordinput + "'"); // Hämtar ut lösenord från lärare genom passwordinput. 
                String behorighetskontroll = idb.fetchSingle("select ADMINISTRATOR from LARARE where ADMINISTRATOR = 'T' AND FORNAMN ='" + txtusername.getText() + "' AND LOSENORD ='" + passwordinput + "'");

                JOptionPane.showMessageDialog(null, "Läraren : " + fornamn + " hittades");

                if (fornamn.equals(txtusername.getText()) && passwordfetch.equals(passwordinput) && behorighetskontroll.equals(behorighetskontroll)) {

                    JOptionPane.showMessageDialog(null, "Du har loggats in!");
                    new AdminMeny().setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Felaktigt Lösenord, lösenordet kunde inte hittas " + passwordfetch + " ");
                }

            } catch (InfException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Denna lärare saknar administratörsstatus!");
            }
        }

        
    }//GEN-LAST:event_LoggainActionPerformed

    private void TillStartMenynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillStartMenynActionPerformed
        // TODO add your handling code here:
        this.hide();
        HuvudMeny frm = new HuvudMeny();
        frm.setVisible(true);

        
    }//GEN-LAST:event_TillStartMenynActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTopText;
    private javax.swing.JButton Loggain;
    private javax.swing.JPanel PanelAdminloggning;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton TillStartMenyn;
    private javax.swing.JLabel lblanvandare;
    private javax.swing.JLabel lbllosenord;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
