/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;


import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Erik
 */
public class AdminChangeElevinfo extends javax.swing.JFrame {
     private static InfDB idb;

    /**
     * Creates new form AdminChangeLarareinfo
     */
    public AdminChangeElevinfo() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB"); //hämtar databasen HOGDB.FDB och namnger med variabelnamnet InfDB
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel"); //felmedellande 
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdminChangeElevInfo = new javax.swing.JPanel();
        lblTopText = new javax.swing.JLabel();
        lblfornamn = new javax.swing.JLabel();
        txtfornamn = new javax.swing.JTextField();
        lblefternamn = new javax.swing.JLabel();
        txtefternamn = new javax.swing.JTextField();
        lblsovsal = new javax.swing.JLabel();
        txtsovsal = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        fetchid = new javax.swing.JButton();
        txteleviid = new javax.swing.JTextField();
        lblelevid = new javax.swing.JLabel();
        lblinfotext = new javax.swing.JLabel();
        nyttid = new javax.swing.JTextField();
        lblnyttid = new javax.swing.JLabel();
        lblnyttfornamn = new javax.swing.JLabel();
        txtnyttfornamn = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTopText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTopText.setText("Ändra elevinformation");

        lblfornamn.setText("Förnamn");

        lblefternamn.setText("Efternamn");

        lblsovsal.setText("Sovsal");

        Update.setText("Ändra");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        fetchid.setText("Hämta ID");
        fetchid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchidActionPerformed(evt);
            }
        });

        lblelevid.setText("ELEV ID");

        lblinfotext.setText("Skriv in ett förnamn, hämta sedan ID, fyll i de andra fälten");

        lblnyttid.setText("Nytt ID");

        lblnyttfornamn.setText("Förnamn");

        back.setText("Tillbaka");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminChangeElevInfoLayout = new javax.swing.GroupLayout(PanelAdminChangeElevInfo);
        PanelAdminChangeElevInfo.setLayout(PanelAdminChangeElevInfoLayout);
        PanelAdminChangeElevInfoLayout.setHorizontalGroup(
            PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminChangeElevInfoLayout.createSequentialGroup()
                .addGroup(PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminChangeElevInfoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(back))
                    .addGroup(PanelAdminChangeElevInfoLayout.createSequentialGroup()
                        .addGroup(PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAdminChangeElevInfoLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelAdminChangeElevInfoLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblinfotext))
                                    .addComponent(lblTopText)))
                            .addGroup(PanelAdminChangeElevInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtefternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelAdminChangeElevInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAdminChangeElevInfoLayout.createSequentialGroup()
                                .addGroup(PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Update)
                                    .addGroup(PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nyttid, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblnyttid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblefternamn)
                                    .addGroup(PanelAdminChangeElevInfoLayout.createSequentialGroup()
                                        .addComponent(txtfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fetchid))
                                    .addComponent(lblfornamn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txteleviid, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminChangeElevInfoLayout.createSequentialGroup()
                                        .addComponent(lblelevid)
                                        .addGap(118, 118, 118))))
                            .addGroup(PanelAdminChangeElevInfoLayout.createSequentialGroup()
                                .addGroup(PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnyttfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblsovsal)
                                    .addComponent(lblnyttfornamn))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(PanelAdminChangeElevInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtsovsal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAdminChangeElevInfoLayout.setVerticalGroup(
            PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminChangeElevInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopText)
                .addGap(8, 8, 8)
                .addComponent(lblinfotext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblelevid)
                    .addComponent(lblfornamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAdminChangeElevInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fetchid)
                    .addComponent(txteleviid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(lblnyttid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nyttid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblsovsal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsovsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblnyttfornamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnyttfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblefternamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtefternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminChangeElevInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminChangeElevInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtnyttfornamn)) // Kallar på valideringsklassen för att kontrollera att textfältet är tomt. 
        {
            try {

                idb.update("update ELEV set FORNAMN ='" + txtnyttfornamn.getText() + "', EFTERNAMN ='" + txtefternamn.getText() + "', SOVSAL ='" + txtsovsal.getText() + "', ELEV_ID ='" + nyttid.getText() + "' where ELEV_ID = '" + txteleviid.getText() + "'");
                // Uppdaterar databasen 

                JOptionPane.showMessageDialog(null, "Informationen har ändrats"); // informerar om att informationen ändrats. 
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());

            }
        }
       
        
    }//GEN-LAST:event_UpdateActionPerformed

    private void fetchidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchidActionPerformed
        // hämtar ut id

        if (Validering.textNotEmpty(txtfornamn)) {
            try {
                String fornamn = txtfornamn.getText(); // hämtar text och placerar i String fornamn. 
                String elevidsearch = idb.fetchSingle("select ELEV_ID from ELEV where FORNAMN ='" + fornamn + "'");     // Placerar ELEV_ID i String elevidsearch.

                txteleviid.setText(elevidsearch);  // Uppdaterar fältet txteleviid med String elevidsearch. 
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println("Internt felmeddelande" + e.getMessage()); // Felmedelande.
                
            }
        }
        
    }//GEN-LAST:event_fetchidActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.hide();
        AdminMeny frm = new AdminMeny(); // Gör adminmeny synlig. 
        frm.setVisible(true);           
        
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChangeElevinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChangeElevinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChangeElevinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChangeElevinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChangeElevinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdminChangeElevInfo;
    private javax.swing.JButton Update;
    private javax.swing.JButton back;
    private javax.swing.JButton fetchid;
    private javax.swing.JLabel lblTopText;
    private javax.swing.JLabel lblefternamn;
    private javax.swing.JLabel lblelevid;
    private javax.swing.JLabel lblfornamn;
    private javax.swing.JLabel lblinfotext;
    private javax.swing.JLabel lblnyttfornamn;
    private javax.swing.JLabel lblnyttid;
    private javax.swing.JLabel lblsovsal;
    private javax.swing.JTextField nyttid;
    private javax.swing.JTextField txtefternamn;
    private javax.swing.JTextField txteleviid;
    private javax.swing.JTextField txtfornamn;
    private javax.swing.JTextField txtnyttfornamn;
    private javax.swing.JTextField txtsovsal;
    // End of variables declaration//GEN-END:variables
}
