/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Jerka
 */
public class AdminRegHuspoang extends javax.swing.JFrame {
    private static InfDB idb;

    /**
     * Creates new form RegHuspoang
     */
    public AdminRegHuspoang() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdminRegHuspoang = new javax.swing.JPanel();
        lblvaljelevhem = new javax.swing.JLabel();
        ComboBoxElevhem = new javax.swing.JComboBox<>();
        OK = new javax.swing.JButton();
        txtelevhem = new javax.swing.JTextField();
        Valj = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblvaljelevhem.setText("Välj elevhem");

        ComboBoxElevhem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gryffindor", "Slytherin", "Ravenclaw", "Hufflepuff", " " }));

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        txtelevhem.setText("<Inget Elevhem har valts>");

        Valj.setText("Välj");
        Valj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValjActionPerformed(evt);
            }
        });

        back.setText("Tillbaka");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminRegHuspoangLayout = new javax.swing.GroupLayout(PanelAdminRegHuspoang);
        PanelAdminRegHuspoang.setLayout(PanelAdminRegHuspoangLayout);
        PanelAdminRegHuspoangLayout.setHorizontalGroup(
            PanelAdminRegHuspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminRegHuspoangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelAdminRegHuspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OK)
                    .addGroup(PanelAdminRegHuspoangLayout.createSequentialGroup()
                        .addComponent(ComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Valj))
                    .addComponent(lblvaljelevhem, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtelevhem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminRegHuspoangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
        );
        PanelAdminRegHuspoangLayout.setVerticalGroup(
            PanelAdminRegHuspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminRegHuspoangLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblvaljelevhem)
                .addGap(20, 20, 20)
                .addGroup(PanelAdminRegHuspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valj, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtelevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminRegHuspoang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminRegHuspoang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed


        if (Validering.textNotEmpty(txtelevhem)) {
            try {

                String poang = txtelevhem.getText();
                String poangSearch = idb.fetchSingle("select HUSPOANG from ELEVHEM where ELEVHEMSNAMN ='" + poang + "'");
                int YesOrNo = JOptionPane.showConfirmDialog(null, "Följande elevhem har " + poangSearch + " poäng \nVill du ändra elevhemmets poäng?");
                switch (YesOrNo) {
                    case 0:

                        new AdminSkrivNyttElevhemsPoang(this.txtelevhem.getText()).setVisible(true);
                        this.setVisible(false);

                        break;
                    case 1:
                        this.hide();
                        LarareMeny frm = new LarareMeny();
                        frm.setVisible(true);
                        break;
                    default:
                        System.exit(0);
                }
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println("Internt felmeddelande" + e.getMessage());

            }
        }


// TODO add your handling code here:
    }//GEN-LAST:event_OKActionPerformed

    private void ValjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValjActionPerformed
        txtelevhem.setText(ComboBoxElevhem.getSelectedItem().toString());

// TODO add your handling code here:
    }//GEN-LAST:event_ValjActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:

        this.hide();
        AdminMeny frm = new AdminMeny();
        frm.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegHuspoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegHuspoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegHuspoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegHuspoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegHuspoang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxElevhem;
    private javax.swing.JButton OK;
    private javax.swing.JPanel PanelAdminRegHuspoang;
    private javax.swing.JButton Valj;
    private javax.swing.JButton back;
    private javax.swing.JLabel lblvaljelevhem;
    public javax.swing.JTextField txtelevhem;
    // End of variables declaration//GEN-END:variables
}
