/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Erik
 */
public class AdminChangeLarareinfo extends javax.swing.JFrame {

    private static InfDB idb;

    /**
     * Creates new form AdminChangeLarareinfo
     */
    public AdminChangeLarareinfo() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB"); //hämtar databasen HOGDB.FDB och namnger med ett variabelnamnet InfDB
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel"); //felmedellande 
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdminChangeLarareInfo = new javax.swing.JPanel();
        lblTopText = new javax.swing.JLabel();
        lblfornamn = new javax.swing.JLabel();
        txtfornamn = new javax.swing.JTextField();
        lblefternamn = new javax.swing.JLabel();
        txtefternamn = new javax.swing.JTextField();
        lbllosenord = new javax.swing.JLabel();
        txtlosenord = new javax.swing.JTextField();
        Andra = new javax.swing.JButton();
        fetchid = new javax.swing.JButton();
        txtlarareid = new javax.swing.JTextField();
        lbllarareid = new javax.swing.JLabel();
        lbltextinfo = new javax.swing.JLabel();
        nyttid = new javax.swing.JTextField();
        lblnyttid = new javax.swing.JLabel();
        lblnyttfornamn = new javax.swing.JLabel();
        txtnyttfornamn = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTopText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTopText.setText("Ändra lärareinformation");

        lblfornamn.setText("Förnamn");

        lblefternamn.setText("Efternamn");

        lbllosenord.setText("Losenord");

        Andra.setText("Ändra");
        Andra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraActionPerformed(evt);
            }
        });

        fetchid.setText("Hämta ID");
        fetchid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchidActionPerformed(evt);
            }
        });

        lbllarareid.setText("Lärarens ID");

        lbltextinfo.setText("Skriv in ett förnamn, hämta sedan ID, fyll i de andra fälten");

        lblnyttid.setText("Nytt ID");

        lblnyttfornamn.setText("Förnamn");

        back.setText("Tillbaka");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminChangeLarareInfoLayout = new javax.swing.GroupLayout(PanelAdminChangeLarareInfo);
        PanelAdminChangeLarareInfo.setLayout(PanelAdminChangeLarareInfoLayout);
        PanelAdminChangeLarareInfoLayout.setHorizontalGroup(
            PanelAdminChangeLarareInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAdminChangeLarareInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                        .addGroup(PanelAdminChangeLarareInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                                .addComponent(txtfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fetchid))
                            .addComponent(lblfornamn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelAdminChangeLarareInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlarareid, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbllarareid))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                        .addGroup(PanelAdminChangeLarareInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblefternamn)
                            .addComponent(lblnyttid)
                            .addComponent(nyttid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtefternamn, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(lblnyttfornamn)
                            .addComponent(Andra)
                            .addComponent(txtnyttfornamn))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                .addGroup(PanelAdminChangeLarareInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                        .addGroup(PanelAdminChangeLarareInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbllosenord))
                            .addGroup(PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtlosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(PanelAdminChangeLarareInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lbltextinfo))
                                    .addComponent(lblTopText))))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(back)))
                .addContainerGap())
        );
        PanelAdminChangeLarareInfoLayout.setVerticalGroup(
            PanelAdminChangeLarareInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminChangeLarareInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopText)
                .addGap(8, 8, 8)
                .addComponent(lbltextinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAdminChangeLarareInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllarareid)
                    .addComponent(lblfornamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAdminChangeLarareInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fetchid)
                    .addComponent(txtlarareid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(lblnyttid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nyttid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblnyttfornamn)
                .addGap(5, 5, 5)
                .addComponent(txtnyttfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblefternamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtefternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbllosenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtlosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Andra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminChangeLarareInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdminChangeLarareInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtnyttfornamn)) // Kontrollerar att textrutan är tom.
        {
            try {

                idb.update("update LARARE set FORNAMN ='" + txtnyttfornamn.getText() + "', EFTERNAMN ='" + txtefternamn.getText() + "', LOSENORD ='" + txtlosenord.getText() + "', LARAR_ID ='" + nyttid.getText() + "' where LARAR_ID = '" + txtlarareid.getText() + "'");

                JOptionPane.showMessageDialog(null, "Informationen har ändrats");  // informerar om att informationen ändrats. 
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());

            }
        }

        
    }//GEN-LAST:event_AndraActionPerformed

    private void fetchidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchidActionPerformed
        // hämtar ut id

        if (Validering.textNotEmpty(txtfornamn)) {
            try {
                String fornamn = txtfornamn.getText();
                String lararidsearch = idb.fetchSingle("select LARAR_ID from LARARE where FORNAMN ='" + fornamn + "'");

                txtlarareid.setText(lararidsearch);
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println("Internt felmeddelande" + e.getMessage());
            }
        }
        
    }//GEN-LAST:event_fetchidActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
this.hide();
        AdminMeny frm = new AdminMeny();
        frm.setVisible(true);      
        
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChangeLarareinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChangeLarareinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChangeLarareinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChangeLarareinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChangeLarareinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Andra;
    private javax.swing.JPanel PanelAdminChangeLarareInfo;
    private javax.swing.JButton back;
    private javax.swing.JButton fetchid;
    private javax.swing.JLabel lblTopText;
    private javax.swing.JLabel lblefternamn;
    private javax.swing.JLabel lblfornamn;
    private javax.swing.JLabel lbllarareid;
    private javax.swing.JLabel lbllosenord;
    private javax.swing.JLabel lblnyttfornamn;
    private javax.swing.JLabel lblnyttid;
    private javax.swing.JLabel lbltextinfo;
    private javax.swing.JTextField nyttid;
    private javax.swing.JTextField txtefternamn;
    private javax.swing.JTextField txtfornamn;
    private javax.swing.JTextField txtlarareid;
    private javax.swing.JTextField txtlosenord;
    private javax.swing.JTextField txtnyttfornamn;
    // End of variables declaration//GEN-END:variables
}
