/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Erik
 */
public class AdminTabortElev extends javax.swing.JFrame {

    private static InfDB idb;

    /**
     * Creates new form AdminTabortLarare
     */
    public AdminTabortElev() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB");  //hämtar databasen HOGDB.FDB och namnger med ett variabelnamnet InfDB
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAdminTabortElev = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        txtelevnamn = new javax.swing.JTextField();
        lblfornamn = new javax.swing.JLabel();
        lbltoptext = new javax.swing.JLabel();
        Tillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        search.setText("Sök");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        lblfornamn.setText("Skriv in elevens förnamn");

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltoptext.setText("Ta bort en elev");

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminTabortElevLayout = new javax.swing.GroupLayout(PanelAdminTabortElev);
        PanelAdminTabortElev.setLayout(PanelAdminTabortElevLayout);
        PanelAdminTabortElevLayout.setHorizontalGroup(
            PanelAdminTabortElevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminTabortElevLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAdminTabortElevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblfornamn)
                    .addComponent(txtelevnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltoptext)
                    .addComponent(search))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminTabortElevLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addContainerGap())
        );
        PanelAdminTabortElevLayout.setVerticalGroup(
            PanelAdminTabortElevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminTabortElevLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lbltoptext)
                .addGap(18, 18, 18)
                .addComponent(lblfornamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtelevnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelAdminTabortElev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelAdminTabortElev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtelevnamn)) {
            try {

                String elev = txtelevnamn.getText();
                String elevsokning = idb.fetchSingle("select FORNAMN from ELEV where FORNAMN ='" + elev + "'");

                int YesOrNo = JOptionPane.showConfirmDialog(null, "Vill du ta bort " + elevsokning + "?");
                switch (YesOrNo) {
                    case 0:

                        idb.delete("DELETE FROM ELEV where FORNAMN= '" + elev + "'");
                        JOptionPane.showMessageDialog(null, "Eleven har tagits bort!");

                        break;
                    case 1:
                        this.hide();
                        AdminMeny frm = new AdminMeny();
                        frm.setVisible(true);
                        break;
                    default:
                        System.exit(0);
                }
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println("Internt felmeddelande" + e.getMessage());

            }
        }


    }//GEN-LAST:event_searchActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        // TODO add your handling code here:
        this.hide();
        AdminMeny frm = new AdminMeny();
        frm.setVisible(true);

    }//GEN-LAST:event_TillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTabortElev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTabortElev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTabortElev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTabortElev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTabortElev().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdminTabortElev;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JLabel lblfornamn;
    private javax.swing.JLabel lbltoptext;
    private javax.swing.JButton search;
    private javax.swing.JTextField txtelevnamn;
    // End of variables declaration//GEN-END:variables
}
