/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Jerka
 */
public class ChangePassword extends javax.swing.JFrame {
    private static InfDB idb;

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB");

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasswordFieldNew = new javax.swing.JPasswordField();
        PasswordFieldConfirm = new javax.swing.JPasswordField();
        Andra = new javax.swing.JButton();
        lblpassword = new javax.swing.JLabel();
        lblconfirmpassword = new javax.swing.JLabel();
        PasswordFieldCurrent = new javax.swing.JPasswordField();
        lblcurrentpassword = new javax.swing.JLabel();
        Tillbaka = new javax.swing.JButton();
        lblusername = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Andra.setText("Ändra");
        Andra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraActionPerformed(evt);
            }
        });

        lblpassword.setText("Nytt lösenord");

        lblconfirmpassword.setText("Bekfräfta lösenord");

        lblcurrentpassword.setText("Nuvarande lösenord");

        Tillbaka.setText("Ångra");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        lblusername.setText("Användarnamn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblusername))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(lblpassword))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblconfirmpassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblcurrentpassword, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PasswordFieldNew, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(PasswordFieldConfirm)
                        .addComponent(PasswordFieldCurrent))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Andra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tillbaka))
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusername)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordFieldCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcurrentpassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordFieldNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblconfirmpassword)
                    .addComponent(PasswordFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Andra)
                    .addComponent(Tillbaka))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        this.hide();
        InloggningLarare frm = new InloggningLarare();
        frm.setVisible(true);

    }//GEN-LAST:event_TillbakaActionPerformed

    private void AndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraActionPerformed
        if (Validering.textNotEmpty(txtusername)) {
            try {

                String username = txtusername.getText();
                String NewPassword = String.valueOf(PasswordFieldNew.getPassword());
                String ConfirmPassword = String.valueOf(PasswordFieldConfirm.getPassword());
                String CurrentPassword = String.valueOf(PasswordFieldCurrent.getPassword());

                String fornamn = idb.fetchSingle("select FORNAMN from LARARE where FORNAMN = '" + username + "'");
                String passwordfetch = idb.fetchSingle("Select LOSENORD from LARARE where LOSENORD ='" + CurrentPassword + "'");

                JOptionPane.showMessageDialog(null, "Användaren " + fornamn + " hittades!");

                JOptionPane.showMessageDialog(null, "Följande " + passwordfetch + " hittades!");

                if (NewPassword.equals(ConfirmPassword)) //bekräfta lösenordet
                {
                    idb.update("UPDATE LARARE SET LOSENORD = '" + NewPassword + "' where FORNAMN ='" + username + "'");
                    JOptionPane.showMessageDialog(null, "Ditt lösenord har ändrats!");
                } else {
                    JOptionPane.showMessageDialog(null, "Dina lösenord matchar inte med varandra, vänligen försök igen!");

                }

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_AndraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Andra;
    private javax.swing.JPasswordField PasswordFieldConfirm;
    private javax.swing.JPasswordField PasswordFieldCurrent;
    private javax.swing.JPasswordField PasswordFieldNew;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JLabel lblconfirmpassword;
    private javax.swing.JLabel lblcurrentpassword;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
