/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

/**
 *
 * @author Erik
 */
public class ElevHuvudMeny extends javax.swing.JFrame {

    /**
     * Creates new form ElevHuvudMeny
     */
    public ElevHuvudMeny() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelElevMeny = new javax.swing.JPanel();
        Tillbaka = new javax.swing.JButton();
        ListaElevhem = new javax.swing.JButton();
        ListaKurser = new javax.swing.JButton();
        SeRegKurser = new javax.swing.JButton();
        StallningElevhemspokalen = new javax.swing.JButton();
        SePrefekt = new javax.swing.JButton();
        SokKursbetyg = new javax.swing.JButton();
        lbltoptext = new javax.swing.JLabel();
        lbltextinfo = new javax.swing.JLabel();
        HamtaBetyg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        ListaElevhem.setText("Lista över all elever i ett visst elevhem");
        ListaElevhem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaElevhemActionPerformed(evt);
            }
        });

        ListaKurser.setText("Lista över vilka kurser en lärare haft mellan två angivna datum");
        ListaKurser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaKurserActionPerformed(evt);
            }
        });

        SeRegKurser.setText("Se registrerade kurser för en elev");
        SeRegKurser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeRegKurserActionPerformed(evt);
            }
        });

        StallningElevhemspokalen.setText("Ställningen i elevhemspokalen");
        StallningElevhemspokalen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StallningElevhemspokalenActionPerformed(evt);
            }
        });

        SePrefekt.setText("Se prefekten för ett visst elevhem");
        SePrefekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SePrefektActionPerformed(evt);
            }
        });

        SokKursbetyg.setText("Sök efter kursbetyg");
        SokKursbetyg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SokKursbetygActionPerformed(evt);
            }
        });

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltoptext.setText("Elevmeny");

        lbltextinfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltextinfo.setText("Välj ett alternativ här nedan");

        HamtaBetyg.setText("Hämta ut betyg för en enskild elev");
        HamtaBetyg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HamtaBetygActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelElevMenyLayout = new javax.swing.GroupLayout(PanelElevMeny);
        PanelElevMeny.setLayout(PanelElevMenyLayout);
        PanelElevMenyLayout.setHorizontalGroup(
            PanelElevMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelElevMenyLayout.createSequentialGroup()
                .addGroup(PanelElevMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelElevMenyLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tillbaka))
                    .addGroup(PanelElevMenyLayout.createSequentialGroup()
                        .addGroup(PanelElevMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelElevMenyLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(PanelElevMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ListaKurser)
                                    .addComponent(ListaElevhem, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SeRegKurser, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StallningElevhemspokalen, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SePrefekt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SokKursbetyg, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltextinfo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HamtaBetyg, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(PanelElevMenyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbltoptext)))
                        .addGap(0, 151, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelElevMenyLayout.setVerticalGroup(
            PanelElevMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelElevMenyLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbltoptext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltextinfo)
                .addGap(29, 29, 29)
                .addComponent(ListaElevhem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListaKurser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeRegKurser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StallningElevhemspokalen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SePrefekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SokKursbetyg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HamtaBetyg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelElevMeny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelElevMeny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        this.hide();
        HuvudMeny frm = new HuvudMeny();
        frm.setVisible(true);
    }//GEN-LAST:event_TillbakaActionPerformed

    private void SePrefektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SePrefektActionPerformed
        new SePrefekt().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_SePrefektActionPerformed

    private void StallningElevhemspokalenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StallningElevhemspokalenActionPerformed

        new PlaceringElevhemspokalen().setVisible(true);
        this.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_StallningElevhemspokalenActionPerformed

    private void ListaElevhemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaElevhemActionPerformed
        // TODO add your handling code here:

        new ListaElevhemsElever().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_ListaElevhemActionPerformed

    private void SokKursbetygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SokKursbetygActionPerformed
        // TODO add your handling code here:
        new KursBetygSokning().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_SokKursbetygActionPerformed

    private void SeRegKurserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeRegKurserActionPerformed
        // TODO add your handling code here:
        new ElevSeRegKurser().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_SeRegKurserActionPerformed

    private void ListaKurserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaKurserActionPerformed
        // TODO add your handling code here:
        new ElevSeLarareForVisstDatum().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListaKurserActionPerformed

    private void HamtaBetygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HamtaBetygActionPerformed
        // TODO add your handling code here:
        new HamtaUtBetygForEnskildElev().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_HamtaBetygActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElevHuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElevHuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElevHuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElevHuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElevHuvudMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HamtaBetyg;
    private javax.swing.JButton ListaElevhem;
    private javax.swing.JButton ListaKurser;
    private javax.swing.JPanel PanelElevMeny;
    private javax.swing.JButton SePrefekt;
    private javax.swing.JButton SeRegKurser;
    private javax.swing.JButton SokKursbetyg;
    private javax.swing.JButton StallningElevhemspokalen;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JLabel lbltextinfo;
    private javax.swing.JLabel lbltoptext;
    // End of variables declaration//GEN-END:variables
}
