/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;


import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;

/**
 *
 * @author Erik
 */
public class ElevSeLarareForVisstDatum extends javax.swing.JFrame {
     private static InfDB idb;

    /**
     * Creates new form ElevSeLarareForVisstDatum
     */
    public ElevSeLarareForVisstDatum() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSeLarareforvisstDatum = new javax.swing.JPanel();
        Tillbaka = new javax.swing.JButton();
        lblfornamn = new javax.swing.JLabel();
        lbltoptext = new javax.swing.JLabel();
        txtkursstart = new javax.swing.JTextField();
        txtkursslut = new javax.swing.JTextField();
        lblkursstart = new javax.swing.JLabel();
        lblkursslut = new javax.swing.JLabel();
        sok = new javax.swing.JButton();
        txtfornamn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        lblfornamn.setText("Skriv in ett lärarens förnamn");

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltoptext.setText("Lista över vilka kurser en lärare haft mellan två angivna datum");

        lblkursstart.setText("Kursstart");

        lblkursslut.setText("Kursslut");

        sok.setText("Sök");
        sok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSeLarareforvisstDatumLayout = new javax.swing.GroupLayout(PanelSeLarareforvisstDatum);
        PanelSeLarareforvisstDatum.setLayout(PanelSeLarareforvisstDatumLayout);
        PanelSeLarareforvisstDatumLayout.setHorizontalGroup(
            PanelSeLarareforvisstDatumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeLarareforvisstDatumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSeLarareforvisstDatumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltoptext)
                    .addComponent(sok)
                    .addGroup(PanelSeLarareforvisstDatumLayout.createSequentialGroup()
                        .addGroup(PanelSeLarareforvisstDatumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkursstart, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblkursstart))
                        .addGap(52, 52, 52)
                        .addGroup(PanelSeLarareforvisstDatumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkursslut, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblkursslut))
                        .addGap(18, 18, 18)
                        .addGroup(PanelSeLarareforvisstDatumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfornamn)
                            .addComponent(txtfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSeLarareforvisstDatumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addContainerGap())
        );
        PanelSeLarareforvisstDatumLayout.setVerticalGroup(
            PanelSeLarareforvisstDatumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSeLarareforvisstDatumLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbltoptext)
                .addGap(41, 41, 41)
                .addGroup(PanelSeLarareforvisstDatumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkursstart)
                    .addComponent(lblkursslut)
                    .addComponent(lblfornamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSeLarareforvisstDatumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkursstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkursslut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSeLarareforvisstDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSeLarareforvisstDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokActionPerformed
        // TODO add your handling code here:
        if (Validering.textNotEmpty(txtkursstart)) {
            try {
                String kursstart = txtkursstart.getText();
                String kursslut = txtkursslut.getText();
                String lararenamn = txtfornamn.getText();

                ArrayList<String> datumsokning = idb.fetchColumn("SELECT KURSNAMN FROM LARARE JOIN KURS ON KURS.KURSLARARE = LARARE.LARAR_ID WHERE KURSSTART ='" + kursstart + "' AND KURSSLUT ='" + kursslut + "'AND FORNAMN ='" + lararenamn + "'");

                JOptionPane.showMessageDialog(null, "Läraren har haft följande kurser " + datumsokning + "!");
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());

            }
        }


    }//GEN-LAST:event_sokActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        // TODO add your handling code here:
        this.hide();
        ElevHuvudMeny frm = new ElevHuvudMeny();
        frm.setVisible(true);


    }//GEN-LAST:event_TillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElevSeLarareForVisstDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElevSeLarareForVisstDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElevSeLarareForVisstDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElevSeLarareForVisstDatum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElevSeLarareForVisstDatum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSeLarareforvisstDatum;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JLabel lblfornamn;
    private javax.swing.JLabel lblkursslut;
    private javax.swing.JLabel lblkursstart;
    private javax.swing.JLabel lbltoptext;
    private javax.swing.JButton sok;
    private javax.swing.JTextField txtfornamn;
    private javax.swing.JTextField txtkursslut;
    private javax.swing.JTextField txtkursstart;
    // End of variables declaration//GEN-END:variables
}
