package HogwartsProjekt;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erik
 */
public class HuvudMeny extends javax.swing.JFrame {

    /**
     * Creates new form HuvudMeny
     */
    public HuvudMeny() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltoptext = new javax.swing.JLabel();
        ELEV = new javax.swing.JButton();
        LARARE = new javax.swing.JButton();
        lbltopinfo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Loggaut = new javax.swing.JButton();
        adminloginin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltoptext.setText("VÄLKOMMEN TILL HOGWARTS");

        ELEV.setText("ELEV");
        ELEV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELEVActionPerformed(evt);
            }
        });

        LARARE.setText("LÄRARE");
        LARARE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LARAREActionPerformed(evt);
            }
        });

        lbltopinfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltopinfo.setText("Välj tillhörighet");

        jLabel3.setText("*kräver lösenord");

        Loggaut.setText("Logga ut");
        Loggaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoggautActionPerformed(evt);
            }
        });

        adminloginin.setText("Adminstratör");
        adminloginin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminlogininActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adminloginin)
                    .addComponent(ELEV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(LARARE))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Loggaut)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltoptext)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lbltopinfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbltoptext)
                .addGap(45, 45, 45)
                .addComponent(lbltopinfo)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ELEV)
                    .addComponent(LARARE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Loggaut)
                    .addComponent(adminloginin))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LARAREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LARAREActionPerformed
        new InloggningLarare().setVisible(true); // Öppnar fönstret InloggingLarare.
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_LARAREActionPerformed

    private void ELEVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELEVActionPerformed
        new ElevHuvudMeny().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_ELEVActionPerformed

    private void LoggautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoggautActionPerformed
        // TODO add your handling code here:

        System.exit(0); // stänger systemet. 

    }//GEN-LAST:event_LoggautActionPerformed

    private void adminlogininActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminlogininActionPerformed
        // TODO add your handling code here:

        new AdminLogin().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_adminlogininActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HuvudMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ELEV;
    private javax.swing.JButton LARARE;
    private javax.swing.JButton Loggaut;
    private javax.swing.JButton adminloginin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbltopinfo;
    private javax.swing.JLabel lbltoptext;
    // End of variables declaration//GEN-END:variables
}
