package HogwartsProjekt;


import HogwartsProjekt.ElevRegistering;
import HogwartsProjekt.ChangeElevInfo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erik
 */
public class LarareMeny extends javax.swing.JFrame {

    /**
     * Creates new form LarareMeny
     */
    public LarareMeny() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLarareMeny = new javax.swing.JPanel();
        NyRegElev = new javax.swing.JButton();
        AndraElevInfo = new javax.swing.JButton();
        AndraHuspoang = new javax.swing.JButton();
        NyttKursbetyg = new javax.swing.JButton();
        AndraBefintligtKursbetyg = new javax.swing.JButton();
        lbltoptext = new javax.swing.JLabel();
        lbltextinfo = new javax.swing.JLabel();
        Tillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NyRegElev.setText("Registrera en ny elev");
        NyRegElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NyRegElevActionPerformed(evt);
            }
        });

        AndraElevInfo.setText("Ändra information för en elev");
        AndraElevInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraElevInfoActionPerformed(evt);
            }
        });

        AndraHuspoang.setText("Ändra Huspoäng");
        AndraHuspoang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraHuspoangActionPerformed(evt);
            }
        });

        NyttKursbetyg.setText("Nytt kursbetyg");
        NyttKursbetyg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NyttKursbetygActionPerformed(evt);
            }
        });

        AndraBefintligtKursbetyg.setText("Ändra befintligt kursbetyg");
        AndraBefintligtKursbetyg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndraBefintligtKursbetygActionPerformed(evt);
            }
        });

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltoptext.setText("Läraremeny");

        lbltextinfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltextinfo.setText("Välj ett alternativ här nedan");

        Tillbaka.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tillbaka.setText("Tillbaka till Startskärm");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLarareMenyLayout = new javax.swing.GroupLayout(PanelLarareMeny);
        PanelLarareMeny.setLayout(PanelLarareMenyLayout);
        PanelLarareMenyLayout.setHorizontalGroup(
            PanelLarareMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLarareMenyLayout.createSequentialGroup()
                .addGroup(PanelLarareMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLarareMenyLayout.createSequentialGroup()
                        .addGroup(PanelLarareMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLarareMenyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelLarareMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NyRegElev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AndraElevInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AndraHuspoang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NyttKursbetyg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AndraBefintligtKursbetyg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(PanelLarareMenyLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbltoptext))
                            .addGroup(PanelLarareMenyLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbltextinfo)))
                        .addGap(0, 207, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLarareMenyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Tillbaka)))
                .addContainerGap())
        );
        PanelLarareMenyLayout.setVerticalGroup(
            PanelLarareMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLarareMenyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltoptext)
                .addGap(18, 18, 18)
                .addComponent(lbltextinfo)
                .addGap(17, 17, 17)
                .addComponent(NyRegElev)
                .addGap(18, 18, 18)
                .addComponent(AndraElevInfo)
                .addGap(18, 18, 18)
                .addComponent(AndraHuspoang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NyttKursbetyg)
                .addGap(18, 18, 18)
                .addComponent(AndraBefintligtKursbetyg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLarareMeny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLarareMeny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NyRegElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NyRegElevActionPerformed
        new ElevRegistering().setVisible(true);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_NyRegElevActionPerformed

    private void AndraElevInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraElevInfoActionPerformed
        new ChangeElevInfo().setVisible(true);
        this.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_AndraElevInfoActionPerformed

    private void AndraHuspoangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraHuspoangActionPerformed
        new RegHuspoang().setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_AndraHuspoangActionPerformed

    private void NyttKursbetygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NyttKursbetygActionPerformed
        // TODO add your handling code here:

        new registeraNyttKursbetyg().setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_NyttKursbetygActionPerformed

    private void AndraBefintligtKursbetygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndraBefintligtKursbetygActionPerformed
        // TODO add your handling code here:

        new UppdateraBetyg().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_AndraBefintligtKursbetygActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        // TODO add your handling code here:
        this.hide();
        HuvudMeny frm = new HuvudMeny();
        frm.setVisible(true);
    }//GEN-LAST:event_TillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LarareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LarareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LarareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LarareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LarareMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AndraBefintligtKursbetyg;
    private javax.swing.JButton AndraElevInfo;
    private javax.swing.JButton AndraHuspoang;
    private javax.swing.JButton NyRegElev;
    private javax.swing.JButton NyttKursbetyg;
    private javax.swing.JPanel PanelLarareMeny;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JLabel lbltextinfo;
    private javax.swing.JLabel lbltoptext;
    // End of variables declaration//GEN-END:variables
}
