package HogwartsProjekt;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.util.ArrayList;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.DefaultListModel;


/**
 *
 * @author Erik
 */
public class ListaElevhemsElever extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form ListaElevhemsElever
     */
    public ListaElevhemsElever() {
        initComponents();

        try {
            idb = new InfDB("C://db//HOGDB.FDB");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltoptext = new javax.swing.JLabel();
        Lista = new javax.swing.JButton();
        txtelevhem = new javax.swing.JTextField();
        lblelevhem = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        Tillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltoptext.setText("Lista alla elever för ett visst elevhem");

        Lista.setText("Lista");
        Lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaActionPerformed(evt);
            }
        });

        lblelevhem.setText("Skriv in ditt elevhem");

        ScrollPane.setViewportView(List);

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtelevhem, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblelevhem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Lista)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tillbaka))
                        .addComponent(lbltoptext, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltoptext)
                .addGap(18, 18, 18)
                .addComponent(lblelevhem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtelevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lista)
                    .addComponent(Tillbaka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaActionPerformed
        if (Validering.textNotEmpty(txtelevhem)) {
            try {
                String vilketElevhem = txtelevhem.getText();
                ArrayList<HashMap<String, String>> elevhemslista = idb.fetchRows("select elev.fornamn, elev.efternamn from elev join sovsal on elev.sovsal = sovsal.SOVSAL_ID join elevhem on sovsal.elevhem = elevhem.elevhem_ID where elevhemsnamn = '" + vilketElevhem + "'");
                //jTextField1.setText(elevhemslista.toString());
                //System.out.println("");

                // for(HashMap<String,String> elev : elevhemslista){
                //   System.out.print(elev.get("NAMN")+ " " + elev.get("EFTERNAMN"));
                //JOptionPane.showMessageDialog(null, elev.get("NAMN")+ " " + elev.get("EFTERNAMN"));
                //}
                DefaultListModel model2 = new DefaultListModel();

                for (HashMap<String, String> elev : elevhemslista) {
                    model2.addElement(elev);
                }
                List.setModel(model2);

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        // TODO add your handling code here:
        this.hide();
        ElevHuvudMeny frm = new ElevHuvudMeny();
        frm.setVisible(true);
    }//GEN-LAST:event_TillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaElevhemsElever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaElevhemsElever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaElevhemsElever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaElevhemsElever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaElevhemsElever().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> List;
    private javax.swing.JButton Lista;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JLabel lblelevhem;
    private javax.swing.JLabel lbltoptext;
    private javax.swing.JTextField txtelevhem;
    // End of variables declaration//GEN-END:variables
}
