/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Erik
 */
public class PlaceringElevhemspokalen extends javax.swing.JFrame {
      private static InfDB idb;

    /**
     * Creates new form PlaceringElevhemspokalen
     */
    public PlaceringElevhemspokalen() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB");

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelElevhemPlaceing = new javax.swing.JPanel();
        lbltoptext = new javax.swing.JLabel();
        ScrollPanePlacering = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        hamta = new javax.swing.JToggleButton();
        lblplacering = new javax.swing.JLabel();
        ScrollPaneHuspoang = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        lblhuspoang = new javax.swing.JLabel();
        ScrollPaneElevhem = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        lblelevhem = new javax.swing.JLabel();
        Tillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltoptext.setText("Ställningen för elevhemspokalen");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ScrollPanePlacering.setViewportView(jList1);

        hamta.setText("Hämta");
        hamta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamtaActionPerformed(evt);
            }
        });

        lblplacering.setText("Placering");

        ScrollPaneHuspoang.setViewportView(jList2);

        lblhuspoang.setText("Huspoang");

        ScrollPaneElevhem.setViewportView(jList3);

        lblelevhem.setText("Elevhem");

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelElevhemPlaceingLayout = new javax.swing.GroupLayout(PanelElevhemPlaceing);
        PanelElevhemPlaceing.setLayout(PanelElevhemPlaceingLayout);
        PanelElevhemPlaceingLayout.setHorizontalGroup(
            PanelElevhemPlaceingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelElevhemPlaceingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelElevhemPlaceingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltoptext)
                    .addGroup(PanelElevhemPlaceingLayout.createSequentialGroup()
                        .addGroup(PanelElevhemPlaceingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrollPanePlacering, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblplacering))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelElevhemPlaceingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrollPaneElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelElevhemPlaceingLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblelevhem)))
                        .addGroup(PanelElevhemPlaceingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelElevhemPlaceingLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblhuspoang))
                            .addGroup(PanelElevhemPlaceingLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ScrollPaneHuspoang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(hamta))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelElevhemPlaceingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tillbaka)
                .addGap(54, 54, 54))
        );
        PanelElevhemPlaceingLayout.setVerticalGroup(
            PanelElevhemPlaceingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelElevhemPlaceingLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbltoptext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hamta)
                .addGap(18, 18, 18)
                .addGroup(PanelElevhemPlaceingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblplacering)
                    .addComponent(lblelevhem)
                    .addComponent(lblhuspoang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelElevhemPlaceingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelElevhemPlaceingLayout.createSequentialGroup()
                        .addGroup(PanelElevhemPlaceingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ScrollPaneElevhem, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(ScrollPanePlacering, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelElevhemPlaceingLayout.createSequentialGroup()
                        .addComponent(ScrollPaneHuspoang, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(Tillbaka)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelElevhemPlaceing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelElevhemPlaceing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hamtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamtaActionPerformed
        // TODO add your handling code here:
        try {

            ArrayList<String> poang = idb.fetchColumn("SELECT HUSPOANG, ELEVHEMSNAMN FROM ELEVHEM Order By Cast (HUSPOANG AS int)DESC");
            ArrayList<String> elevhemsnamn = idb.fetchColumn("SELECT ELEVHEMSNAMN FROM ELEVHEM Order By Cast (HUSPOANG AS int)DESC");

            DefaultListModel model2 = new DefaultListModel();

            for (String lista : poang) {
                model2.addElement(lista);
            }
            jList2.setModel(model2);

            DefaultListModel model3 = new DefaultListModel();

            for (String elevhemslista : elevhemsnamn) {
                model3.addElement(elevhemslista);
            }
            jList3.setModel(model3);

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }


    }//GEN-LAST:event_hamtaActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        // TODO add your handling code here:
        this.hide();
        ElevHuvudMeny frm = new ElevHuvudMeny();
        frm.setVisible(true);


    }//GEN-LAST:event_TillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceringElevhemspokalen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceringElevhemspokalen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceringElevhemspokalen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceringElevhemspokalen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceringElevhemspokalen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelElevhemPlaceing;
    private javax.swing.JScrollPane ScrollPaneElevhem;
    private javax.swing.JScrollPane ScrollPaneHuspoang;
    private javax.swing.JScrollPane ScrollPanePlacering;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JToggleButton hamta;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JLabel lblelevhem;
    private javax.swing.JLabel lblhuspoang;
    private javax.swing.JLabel lblplacering;
    private javax.swing.JLabel lbltoptext;
    // End of variables declaration//GEN-END:variables
}
