/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Jerka
 */
public class RegHuspoang extends javax.swing.JFrame {
    private static InfDB idb;

    /**
     * Creates new form RegHuspoang
     */
    public RegHuspoang() {
        initComponents();
        try {
            idb = new InfDB("C://db//HOGDB.FDB");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegHuspoang = new javax.swing.JPanel();
        lbltoptextinfo = new javax.swing.JLabel();
        ComboBoxElevhem = new javax.swing.JComboBox<>();
        ok = new javax.swing.JButton();
        txtelevhem = new javax.swing.JTextField();
        valj = new javax.swing.JButton();
        lbltoptext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltoptextinfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltoptextinfo.setText("Välj elevhem");

        ComboBoxElevhem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gryffindor", "Slytherin", "Ravenclaw", "Hufflepuff", " " }));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        txtelevhem.setText("<Inget Elevhem har valts>");

        valj.setText("Välj");
        valj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valjActionPerformed(evt);
            }
        });

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltoptext.setText("Registerera nya poäng");

        javax.swing.GroupLayout PanelRegHuspoangLayout = new javax.swing.GroupLayout(PanelRegHuspoang);
        PanelRegHuspoang.setLayout(PanelRegHuspoangLayout);
        PanelRegHuspoangLayout.setHorizontalGroup(
            PanelRegHuspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegHuspoangLayout.createSequentialGroup()
                .addGroup(PanelRegHuspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegHuspoangLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PanelRegHuspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ok)
                            .addGroup(PanelRegHuspoangLayout.createSequentialGroup()
                                .addComponent(ComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valj))
                            .addComponent(lbltoptextinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtelevhem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelRegHuspoangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbltoptext)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        PanelRegHuspoangLayout.setVerticalGroup(
            PanelRegHuspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegHuspoangLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbltoptext)
                .addGap(18, 18, 18)
                .addComponent(lbltoptextinfo)
                .addGap(18, 18, 18)
                .addGroup(PanelRegHuspoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboBoxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valj, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtelevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ok)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegHuspoang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegHuspoang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        if (Validering.textNotEmpty(txtelevhem)) {
            try {

                String poang = txtelevhem.getText();
                String poangSearch = idb.fetchSingle("select HUSPOANG from ELEVHEM where ELEVHEMSNAMN ='" + poang + "'");
                int YesOrNo = JOptionPane.showConfirmDialog(null, "Följande elevhem har " + poangSearch + " poäng \nVill du ändra elevhemmets poäng?");
                switch (YesOrNo) {
                    case 0:

                        new SkrivNyttElevhemsPoang(this.txtelevhem.getText()).setVisible(true);
                        this.setVisible(false);

                        break;
                    case 1:
                        this.hide();
                        LarareMeny frm = new LarareMeny();
                        frm.setVisible(true);
                        break;
                    default:
                        System.exit(0);
                }
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println("Internt felmeddelande" + e.getMessage());

            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_okActionPerformed

    private void valjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valjActionPerformed
        txtelevhem.setText(ComboBoxElevhem.getSelectedItem().toString());

// TODO add your handling code here:
    }//GEN-LAST:event_valjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegHuspoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegHuspoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegHuspoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegHuspoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegHuspoang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxElevhem;
    private javax.swing.JPanel PanelRegHuspoang;
    private javax.swing.JLabel lbltoptext;
    private javax.swing.JLabel lbltoptextinfo;
    private javax.swing.JButton ok;
    public javax.swing.JTextField txtelevhem;
    private javax.swing.JButton valj;
    // End of variables declaration//GEN-END:variables
}
