/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HogwartsProjekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Jerka
 */
public class SkrivNyttElevhemsPoang extends javax.swing.JFrame {
    private static InfDB idb;
//public static String txtelevhem;

    /**
     * Creates new form SkrivNyttElevhemsPoang
     */
    public SkrivNyttElevhemsPoang(String txtelevhem) {
        initComponents();
        txtelevhemsnamn.setText(txtelevhem);
        try {
            idb = new InfDB("C://db//HOGDB.FDB");

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick visst fel");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }
    }

    public SkrivNyttElevhemsPoang() {
        initComponents();

    }

//public SkrivNyttElevhemsPoang(String para){
    //      initComponents();
    //   txtelevhem.setText(para);
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegNyPoang = new javax.swing.JPanel();
        lblnyapoang = new javax.swing.JLabel();
        txtpoang = new javax.swing.JTextField();
        Registrera = new javax.swing.JButton();
        txtelevhemsnamn = new javax.swing.JTextField();
        lblvisaelevhem = new javax.swing.JLabel();
        Tillbaka = new javax.swing.JButton();
        lbltoptext = new javax.swing.JLabel();
        valjannatelevhem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnyapoang.setText("Skriv in nya poäng");

        Registrera.setText("Registrera");
        Registrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistreraActionPerformed(evt);
            }
        });

        txtelevhemsnamn.setBackground(new java.awt.Color(204, 204, 255));
        txtelevhemsnamn.setCaretColor(new java.awt.Color(204, 204, 204));

        lblvisaelevhem.setText("Ändrar följande elevhems poäng");

        Tillbaka.setText("Tillbaka");
        Tillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TillbakaActionPerformed(evt);
            }
        });

        lbltoptext.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltoptext.setText("Registera nya huspoäng");

        valjannatelevhem.setText("Välj ett annat elevhem");
        valjannatelevhem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valjannatelevhemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRegNyPoangLayout = new javax.swing.GroupLayout(PanelRegNyPoang);
        PanelRegNyPoang.setLayout(PanelRegNyPoangLayout);
        PanelRegNyPoangLayout.setHorizontalGroup(
            PanelRegNyPoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegNyPoangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegNyPoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltoptext)
                    .addComponent(lblnyapoang)
                    .addComponent(txtpoang, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registrera)
                    .addGroup(PanelRegNyPoangLayout.createSequentialGroup()
                        .addComponent(lblvisaelevhem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtelevhemsnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegNyPoangLayout.createSequentialGroup()
                        .addComponent(valjannatelevhem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tillbaka)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PanelRegNyPoangLayout.setVerticalGroup(
            PanelRegNyPoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegNyPoangLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lbltoptext)
                .addGap(36, 36, 36)
                .addGroup(PanelRegNyPoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvisaelevhem, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtelevhemsnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblnyapoang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpoang, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Registrera)
                .addGap(18, 18, 18)
                .addGroup(PanelRegNyPoangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valjannatelevhem)
                    .addComponent(Tillbaka))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegNyPoang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegNyPoang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistreraActionPerformed
        if (Validering.textNotEmpty(txtpoang)) {
            try {
                String NyaPoang = txtpoang.getText();
                String elevhemsnamn = txtelevhemsnamn.getText();

                idb.update("UPDATE ELEVHEM SET HUSPOANG = '" + NyaPoang + "' where ELEVHEMSNAMN ='" + elevhemsnamn + "'");
                JOptionPane.showMessageDialog(null, " " + elevhemsnamn + " har tilldelats " + NyaPoang + " poäng!");
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick visst fel");
                System.out.println("Internt felmeddelande" + e.getMessage());

            }
        }

    }//GEN-LAST:event_RegistreraActionPerformed

    private void TillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TillbakaActionPerformed
        this.hide();
        LarareMeny frm = new LarareMeny();
        frm.setVisible(true);

// Tar användaren tillbaka till huvudmenyn
    }//GEN-LAST:event_TillbakaActionPerformed

    private void valjannatelevhemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valjannatelevhemActionPerformed
        // TODO add your handling code here:
        this.hide();
        RegHuspoang frm = new RegHuspoang();
        frm.setVisible(true);
    }//GEN-LAST:event_valjannatelevhemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //txtelevhem=args[0];
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkrivNyttElevhemsPoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkrivNyttElevhemsPoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkrivNyttElevhemsPoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkrivNyttElevhemsPoang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkrivNyttElevhemsPoang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelRegNyPoang;
    private javax.swing.JButton Registrera;
    private javax.swing.JButton Tillbaka;
    private javax.swing.JLabel lblnyapoang;
    private javax.swing.JLabel lbltoptext;
    private javax.swing.JLabel lblvisaelevhem;
    public javax.swing.JTextField txtelevhemsnamn;
    public javax.swing.JTextField txtpoang;
    private javax.swing.JButton valjannatelevhem;
    // End of variables declaration//GEN-END:variables
}
